# ==============================================================================
# FICHIER DE CONFIGURATION PRINCIPAL NETLIFY POUR BMS VENTOUSE
# ==============================================================================
# Ce fichier est la source de vérité unique pour la configuration du build,
# des redirections et des en-têtes HTTP.
# Les fichiers _headers et _redirects ne sont plus nécessaires.

# ------------------------------------------------------------------------------
# SECTION BUILD : Instructions pour construire le site
# ------------------------------------------------------------------------------
[build]
  # Commande pour installer les dépendances et lancer le build
  command = "npm install && npm run build"

  # Dossier final à publier sur Netlify (généré par Eleventy)
  publish = "_site"

  # Contexte de production
  [build.environment]
    # Force l'utilisation d'une version stable de Node.js pour la fiabilité
    NODE_VERSION = "18"


# ------------------------------------------------------------------------------
# SECTION HEADERS : En-têtes HTTP pour la sécurité et la performance
# ------------------------------------------------------------------------------
[[headers]]
  # Règle globale appliquée à toutes les pages
  for = "/*"
  [headers.values]
    # Sécurité : Force la communication en HTTPS
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # Sécurité : Empêche le clickjacking
    X-Frame-Options = "DENY"
    # Sécurité : Force le respect des types de contenu
    X-Content-Type-Options = "nosniff"
    # Sécurité : Désactive l'ancien filtre XSS (la CSP est plus efficace)
    X-XSS-Protection = "0"
    # Vie privée : Contrôle les informations de provenance
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Sécurité : Bloque les API du navigateur non utilisées
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), usb=()"
    # Sécurité : Liste blanche des sources de contenu (CSP)
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self'; img-src 'self' data: https:; font-src 'self' https:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'"

[[headers]]
  # Cache longue durée pour les assets (chemins adaptés à la structure finale)
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # HTML non mis en cache pour voir les mises à jour immédiatement
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"


# ------------------------------------------------------------------------------
# SECTION REDIRECTS : Redirections d'URL
# ------------------------------------------------------------------------------
# Alias pour la page d'accueil
[[redirects]]
  from = "/accueil"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = false

# Raccourcis vers les sections de la page d'accueil
[[redirects]]
  from = "/services"
  to = "/#services"
  status = 301
  force = false

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301
  force = false

[[redirects]]
  from = "/realisations"
  to = "/#realisations"
  status = 301
  force = false

# Gestion de la page 404 (Page non trouvée)
# Affiche le contenu de /404.html sans changer l'URL (meilleur pour le SEO)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
